### ISSUE TITLE
Linker error on mac os continuous integration tests

### ISSUE THREAD

**Issue by alecjacobson** [libigl/libigl#2383]
```
Assertion failed: (extras.otherInstrOffset != 0 && "Kind::arm64_adrp_ldr missing extra info"), function applyFixup, file Fixup.cpp, line 793.
```

Seems to be this: https://forums.developer.apple.com/forums/thread/739993

Looks like we need a bugfix on xcode on the github action servers. I'm not sure how to do that.

**Comment by jdumas** [comment]
The new linker that comes with Xcode 15.0 is seriously bugged. I suggest using Xcode 15.1 or 15.2 in GitHub Actions. Here is what I use [in Lagrange](https://github.com/adobe/lagrange/blob/930f894ccac1157ba318f6029aa3c7d4afc7fd1c/.github/workflows/continuous.yaml#L92-L96) to switch:

```yaml
      - name: Setup Xcode version
        if: runner.os == 'macOS'
        uses: maxim-lobanov/setup-xcode@v1
        with:
          xcode-version: '15.2'
```
